# Generated by Django 5.1.2 on 2024-10-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("telefone", models.CharField(max_length=20)),
                ("endereco", models.CharField(blank=True, max_length=100)),
                ("cidade", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=50)),
                ("cep", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="Dados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nasc", models.DateField()),
                ("cpf", models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=100, null=True)),
                ("empresa", models.CharField(max_length=100, null=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curso", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "instituicao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Curriculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "contato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="curriculos.contato",
                    ),
                ),
                (
                    "dados",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="curriculos.dados",
                    ),
                ),
                (
                    "experiencia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="curriculos.experiencia",
                    ),
                ),
                (
                    "formacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="curriculos.formacao",
                    ),
                ),
            ],
        ),
    ]
