# Generated by Django 5.1.2 on 2024-10-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculos", "0002_alter_contato_cep_alter_contato_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencia",
            name="data_fim",
            field=models.DateField(blank=True, default="0000/00/00", null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="data_inicio",
            field=models.DateField(blank=True, default="0000/00/00", null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="data_fim",
            field=models.DateField(blank=True, default="0000/00/00", null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="data_inicio",
            field=models.DateField(blank=True, default="0000/00/00", null=True),
        ),
    ]
