# Generated by Django 5.1.2 on 2024-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculos", "0003_alter_experiencia_data_fim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencia",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
